/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelIndexRouteImport } from './routes/panel.index'
import { Route as PanelVendedorRouteImport } from './routes/panel.vendedor'
import { Route as PanelSoporteRouteImport } from './routes/panel.soporte'
import { Route as PanelSeguimientoRouteImport } from './routes/panel.seguimiento'
import { Route as PanelReportesRouteImport } from './routes/panel.reportes'
import { Route as PanelProveedoresRouteImport } from './routes/panel.proveedores'
import { Route as PanelPreordenesRouteImport } from './routes/panel.preordenes'
import { Route as PanelPortalProveedorRouteImport } from './routes/panel.portal-proveedor'
import { Route as PanelPeoplesoftRouteImport } from './routes/panel.peoplesoft'
import { Route as PanelNotificacionesRouteImport } from './routes/panel.notificaciones'
import { Route as PanelFlujoRouteImport } from './routes/panel.flujo'
import { Route as PanelConfiguracionRouteImport } from './routes/panel.configuracion'
import { Route as PanelAuditoriaRouteImport } from './routes/panel.auditoria'
import { Route as PanelPreordenesIdRouteImport } from './routes/panel.preordenes.$id'
import { Route as PanelPeoplesoftCatalogosRouteImport } from './routes/panel.peoplesoft.catalogos'

const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelVendedorRoute = PanelVendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSoporteRoute = PanelSoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSeguimientoRoute = PanelSeguimientoRouteImport.update({
  id: '/seguimiento',
  path: '/seguimiento',
  getParentRoute: () => PanelRoute,
} as any)
const PanelReportesRoute = PanelReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => PanelRoute,
} as any)
const PanelProveedoresRoute = PanelProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPreordenesRoute = PanelPreordenesRouteImport.update({
  id: '/preordenes',
  path: '/preordenes',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPortalProveedorRoute = PanelPortalProveedorRouteImport.update({
  id: '/portal-proveedor',
  path: '/portal-proveedor',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPeoplesoftRoute = PanelPeoplesoftRouteImport.update({
  id: '/peoplesoft',
  path: '/peoplesoft',
  getParentRoute: () => PanelRoute,
} as any)
const PanelNotificacionesRoute = PanelNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => PanelRoute,
} as any)
const PanelFlujoRoute = PanelFlujoRouteImport.update({
  id: '/flujo',
  path: '/flujo',
  getParentRoute: () => PanelRoute,
} as any)
const PanelConfiguracionRoute = PanelConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAuditoriaRoute = PanelAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPreordenesIdRoute = PanelPreordenesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PanelPreordenesRoute,
} as any)
const PanelPeoplesoftCatalogosRoute =
  PanelPeoplesoftCatalogosRouteImport.update({
    id: '/catalogos',
    path: '/catalogos',
    getParentRoute: () => PanelPeoplesoftRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/auditoria': typeof PanelAuditoriaRoute
  '/panel/configuracion': typeof PanelConfiguracionRoute
  '/panel/flujo': typeof PanelFlujoRoute
  '/panel/notificaciones': typeof PanelNotificacionesRoute
  '/panel/peoplesoft': typeof PanelPeoplesoftRouteWithChildren
  '/panel/portal-proveedor': typeof PanelPortalProveedorRoute
  '/panel/preordenes': typeof PanelPreordenesRouteWithChildren
  '/panel/proveedores': typeof PanelProveedoresRoute
  '/panel/reportes': typeof PanelReportesRoute
  '/panel/seguimiento': typeof PanelSeguimientoRoute
  '/panel/soporte': typeof PanelSoporteRoute
  '/panel/vendedor': typeof PanelVendedorRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/peoplesoft/catalogos': typeof PanelPeoplesoftCatalogosRoute
  '/panel/preordenes/$id': typeof PanelPreordenesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel/auditoria': typeof PanelAuditoriaRoute
  '/panel/configuracion': typeof PanelConfiguracionRoute
  '/panel/flujo': typeof PanelFlujoRoute
  '/panel/notificaciones': typeof PanelNotificacionesRoute
  '/panel/peoplesoft': typeof PanelPeoplesoftRouteWithChildren
  '/panel/portal-proveedor': typeof PanelPortalProveedorRoute
  '/panel/preordenes': typeof PanelPreordenesRouteWithChildren
  '/panel/proveedores': typeof PanelProveedoresRoute
  '/panel/reportes': typeof PanelReportesRoute
  '/panel/seguimiento': typeof PanelSeguimientoRoute
  '/panel/soporte': typeof PanelSoporteRoute
  '/panel/vendedor': typeof PanelVendedorRoute
  '/panel': typeof PanelIndexRoute
  '/panel/peoplesoft/catalogos': typeof PanelPeoplesoftCatalogosRoute
  '/panel/preordenes/$id': typeof PanelPreordenesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/auditoria': typeof PanelAuditoriaRoute
  '/panel/configuracion': typeof PanelConfiguracionRoute
  '/panel/flujo': typeof PanelFlujoRoute
  '/panel/notificaciones': typeof PanelNotificacionesRoute
  '/panel/peoplesoft': typeof PanelPeoplesoftRouteWithChildren
  '/panel/portal-proveedor': typeof PanelPortalProveedorRoute
  '/panel/preordenes': typeof PanelPreordenesRouteWithChildren
  '/panel/proveedores': typeof PanelProveedoresRoute
  '/panel/reportes': typeof PanelReportesRoute
  '/panel/seguimiento': typeof PanelSeguimientoRoute
  '/panel/soporte': typeof PanelSoporteRoute
  '/panel/vendedor': typeof PanelVendedorRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/peoplesoft/catalogos': typeof PanelPeoplesoftCatalogosRoute
  '/panel/preordenes/$id': typeof PanelPreordenesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/panel'
    | '/panel/auditoria'
    | '/panel/configuracion'
    | '/panel/flujo'
    | '/panel/notificaciones'
    | '/panel/peoplesoft'
    | '/panel/portal-proveedor'
    | '/panel/preordenes'
    | '/panel/proveedores'
    | '/panel/reportes'
    | '/panel/seguimiento'
    | '/panel/soporte'
    | '/panel/vendedor'
    | '/panel/'
    | '/panel/peoplesoft/catalogos'
    | '/panel/preordenes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/panel/auditoria'
    | '/panel/configuracion'
    | '/panel/flujo'
    | '/panel/notificaciones'
    | '/panel/peoplesoft'
    | '/panel/portal-proveedor'
    | '/panel/preordenes'
    | '/panel/proveedores'
    | '/panel/reportes'
    | '/panel/seguimiento'
    | '/panel/soporte'
    | '/panel/vendedor'
    | '/panel'
    | '/panel/peoplesoft/catalogos'
    | '/panel/preordenes/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/panel'
    | '/panel/auditoria'
    | '/panel/configuracion'
    | '/panel/flujo'
    | '/panel/notificaciones'
    | '/panel/peoplesoft'
    | '/panel/portal-proveedor'
    | '/panel/preordenes'
    | '/panel/proveedores'
    | '/panel/reportes'
    | '/panel/seguimiento'
    | '/panel/soporte'
    | '/panel/vendedor'
    | '/panel/'
    | '/panel/peoplesoft/catalogos'
    | '/panel/preordenes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PanelRoute: typeof PanelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/vendedor': {
      id: '/panel/vendedor'
      path: '/vendedor'
      fullPath: '/panel/vendedor'
      preLoaderRoute: typeof PanelVendedorRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/soporte': {
      id: '/panel/soporte'
      path: '/soporte'
      fullPath: '/panel/soporte'
      preLoaderRoute: typeof PanelSoporteRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/seguimiento': {
      id: '/panel/seguimiento'
      path: '/seguimiento'
      fullPath: '/panel/seguimiento'
      preLoaderRoute: typeof PanelSeguimientoRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/reportes': {
      id: '/panel/reportes'
      path: '/reportes'
      fullPath: '/panel/reportes'
      preLoaderRoute: typeof PanelReportesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/proveedores': {
      id: '/panel/proveedores'
      path: '/proveedores'
      fullPath: '/panel/proveedores'
      preLoaderRoute: typeof PanelProveedoresRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/preordenes': {
      id: '/panel/preordenes'
      path: '/preordenes'
      fullPath: '/panel/preordenes'
      preLoaderRoute: typeof PanelPreordenesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/portal-proveedor': {
      id: '/panel/portal-proveedor'
      path: '/portal-proveedor'
      fullPath: '/panel/portal-proveedor'
      preLoaderRoute: typeof PanelPortalProveedorRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/peoplesoft': {
      id: '/panel/peoplesoft'
      path: '/peoplesoft'
      fullPath: '/panel/peoplesoft'
      preLoaderRoute: typeof PanelPeoplesoftRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/notificaciones': {
      id: '/panel/notificaciones'
      path: '/notificaciones'
      fullPath: '/panel/notificaciones'
      preLoaderRoute: typeof PanelNotificacionesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/flujo': {
      id: '/panel/flujo'
      path: '/flujo'
      fullPath: '/panel/flujo'
      preLoaderRoute: typeof PanelFlujoRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/configuracion': {
      id: '/panel/configuracion'
      path: '/configuracion'
      fullPath: '/panel/configuracion'
      preLoaderRoute: typeof PanelConfiguracionRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/auditoria': {
      id: '/panel/auditoria'
      path: '/auditoria'
      fullPath: '/panel/auditoria'
      preLoaderRoute: typeof PanelAuditoriaRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/preordenes/$id': {
      id: '/panel/preordenes/$id'
      path: '/$id'
      fullPath: '/panel/preordenes/$id'
      preLoaderRoute: typeof PanelPreordenesIdRouteImport
      parentRoute: typeof PanelPreordenesRoute
    }
    '/panel/peoplesoft/catalogos': {
      id: '/panel/peoplesoft/catalogos'
      path: '/catalogos'
      fullPath: '/panel/peoplesoft/catalogos'
      preLoaderRoute: typeof PanelPeoplesoftCatalogosRouteImport
      parentRoute: typeof PanelPeoplesoftRoute
    }
  }
}

interface PanelPeoplesoftRouteChildren {
  PanelPeoplesoftCatalogosRoute: typeof PanelPeoplesoftCatalogosRoute
}

const PanelPeoplesoftRouteChildren: PanelPeoplesoftRouteChildren = {
  PanelPeoplesoftCatalogosRoute: PanelPeoplesoftCatalogosRoute,
}

const PanelPeoplesoftRouteWithChildren = PanelPeoplesoftRoute._addFileChildren(
  PanelPeoplesoftRouteChildren,
)

interface PanelPreordenesRouteChildren {
  PanelPreordenesIdRoute: typeof PanelPreordenesIdRoute
}

const PanelPreordenesRouteChildren: PanelPreordenesRouteChildren = {
  PanelPreordenesIdRoute: PanelPreordenesIdRoute,
}

const PanelPreordenesRouteWithChildren = PanelPreordenesRoute._addFileChildren(
  PanelPreordenesRouteChildren,
)

interface PanelRouteChildren {
  PanelAuditoriaRoute: typeof PanelAuditoriaRoute
  PanelConfiguracionRoute: typeof PanelConfiguracionRoute
  PanelFlujoRoute: typeof PanelFlujoRoute
  PanelNotificacionesRoute: typeof PanelNotificacionesRoute
  PanelPeoplesoftRoute: typeof PanelPeoplesoftRouteWithChildren
  PanelPortalProveedorRoute: typeof PanelPortalProveedorRoute
  PanelPreordenesRoute: typeof PanelPreordenesRouteWithChildren
  PanelProveedoresRoute: typeof PanelProveedoresRoute
  PanelReportesRoute: typeof PanelReportesRoute
  PanelSeguimientoRoute: typeof PanelSeguimientoRoute
  PanelSoporteRoute: typeof PanelSoporteRoute
  PanelVendedorRoute: typeof PanelVendedorRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelAuditoriaRoute: PanelAuditoriaRoute,
  PanelConfiguracionRoute: PanelConfiguracionRoute,
  PanelFlujoRoute: PanelFlujoRoute,
  PanelNotificacionesRoute: PanelNotificacionesRoute,
  PanelPeoplesoftRoute: PanelPeoplesoftRouteWithChildren,
  PanelPortalProveedorRoute: PanelPortalProveedorRoute,
  PanelPreordenesRoute: PanelPreordenesRouteWithChildren,
  PanelProveedoresRoute: PanelProveedoresRoute,
  PanelReportesRoute: PanelReportesRoute,
  PanelSeguimientoRoute: PanelSeguimientoRoute,
  PanelSoporteRoute: PanelSoporteRoute,
  PanelVendedorRoute: PanelVendedorRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PanelRoute: PanelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
