/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as DashboardSupplierPortalRouteImport } from './routes/dashboard.supplier-portal'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSalesRepRouteImport } from './routes/dashboard.sales-rep'
import { Route as DashboardResolutionsRouteImport } from './routes/dashboard.resolutions'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardProvidersRouteImport } from './routes/dashboard.providers'
import { Route as DashboardPreordersRouteImport } from './routes/dashboard.preorders'
import { Route as DashboardPeoplesoftRouteImport } from './routes/dashboard.peoplesoft'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardApprovalsRouteImport } from './routes/dashboard.approvals'
import { Route as DashboardPreordersIdRouteImport } from './routes/dashboard.preorders.$id'
import { Route as DashboardPeoplesoftLookupsRouteImport } from './routes/dashboard.peoplesoft.lookups'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupplierPortalRoute = DashboardSupplierPortalRouteImport.update({
  id: '/supplier-portal',
  path: '/supplier-portal',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSalesRepRoute = DashboardSalesRepRouteImport.update({
  id: '/sales-rep',
  path: '/sales-rep',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResolutionsRoute = DashboardResolutionsRouteImport.update({
  id: '/resolutions',
  path: '/resolutions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProvidersRoute = DashboardProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPreordersRoute = DashboardPreordersRouteImport.update({
  id: '/preorders',
  path: '/preorders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPeoplesoftRoute = DashboardPeoplesoftRouteImport.update({
  id: '/peoplesoft',
  path: '/peoplesoft',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPreordersIdRoute = DashboardPreordersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardPreordersRoute,
} as any)
const DashboardPeoplesoftLookupsRoute =
  DashboardPeoplesoftLookupsRouteImport.update({
    id: '/lookups',
    path: '/lookups',
    getParentRoute: () => DashboardPeoplesoftRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/peoplesoft': typeof DashboardPeoplesoftRouteWithChildren
  '/dashboard/preorders': typeof DashboardPreordersRouteWithChildren
  '/dashboard/providers': typeof DashboardProvidersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/resolutions': typeof DashboardResolutionsRoute
  '/dashboard/sales-rep': typeof DashboardSalesRepRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/supplier-portal': typeof DashboardSupplierPortalRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/peoplesoft/lookups': typeof DashboardPeoplesoftLookupsRoute
  '/dashboard/preorders/$id': typeof DashboardPreordersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/peoplesoft': typeof DashboardPeoplesoftRouteWithChildren
  '/dashboard/preorders': typeof DashboardPreordersRouteWithChildren
  '/dashboard/providers': typeof DashboardProvidersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/resolutions': typeof DashboardResolutionsRoute
  '/dashboard/sales-rep': typeof DashboardSalesRepRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/supplier-portal': typeof DashboardSupplierPortalRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/peoplesoft/lookups': typeof DashboardPeoplesoftLookupsRoute
  '/dashboard/preorders/$id': typeof DashboardPreordersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/peoplesoft': typeof DashboardPeoplesoftRouteWithChildren
  '/dashboard/preorders': typeof DashboardPreordersRouteWithChildren
  '/dashboard/providers': typeof DashboardProvidersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/resolutions': typeof DashboardResolutionsRoute
  '/dashboard/sales-rep': typeof DashboardSalesRepRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/supplier-portal': typeof DashboardSupplierPortalRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/peoplesoft/lookups': typeof DashboardPeoplesoftLookupsRoute
  '/dashboard/preorders/$id': typeof DashboardPreordersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/approvals'
    | '/dashboard/audit'
    | '/dashboard/notifications'
    | '/dashboard/peoplesoft'
    | '/dashboard/preorders'
    | '/dashboard/providers'
    | '/dashboard/reports'
    | '/dashboard/resolutions'
    | '/dashboard/sales-rep'
    | '/dashboard/settings'
    | '/dashboard/supplier-portal'
    | '/dashboard/support'
    | '/dashboard/'
    | '/dashboard/peoplesoft/lookups'
    | '/dashboard/preorders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/approvals'
    | '/dashboard/audit'
    | '/dashboard/notifications'
    | '/dashboard/peoplesoft'
    | '/dashboard/preorders'
    | '/dashboard/providers'
    | '/dashboard/reports'
    | '/dashboard/resolutions'
    | '/dashboard/sales-rep'
    | '/dashboard/settings'
    | '/dashboard/supplier-portal'
    | '/dashboard/support'
    | '/dashboard'
    | '/dashboard/peoplesoft/lookups'
    | '/dashboard/preorders/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/approvals'
    | '/dashboard/audit'
    | '/dashboard/notifications'
    | '/dashboard/peoplesoft'
    | '/dashboard/preorders'
    | '/dashboard/providers'
    | '/dashboard/reports'
    | '/dashboard/resolutions'
    | '/dashboard/sales-rep'
    | '/dashboard/settings'
    | '/dashboard/supplier-portal'
    | '/dashboard/support'
    | '/dashboard/'
    | '/dashboard/peoplesoft/lookups'
    | '/dashboard/preorders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/supplier-portal': {
      id: '/dashboard/supplier-portal'
      path: '/supplier-portal'
      fullPath: '/dashboard/supplier-portal'
      preLoaderRoute: typeof DashboardSupplierPortalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sales-rep': {
      id: '/dashboard/sales-rep'
      path: '/sales-rep'
      fullPath: '/dashboard/sales-rep'
      preLoaderRoute: typeof DashboardSalesRepRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resolutions': {
      id: '/dashboard/resolutions'
      path: '/resolutions'
      fullPath: '/dashboard/resolutions'
      preLoaderRoute: typeof DashboardResolutionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/providers': {
      id: '/dashboard/providers'
      path: '/providers'
      fullPath: '/dashboard/providers'
      preLoaderRoute: typeof DashboardProvidersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preorders': {
      id: '/dashboard/preorders'
      path: '/preorders'
      fullPath: '/dashboard/preorders'
      preLoaderRoute: typeof DashboardPreordersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/peoplesoft': {
      id: '/dashboard/peoplesoft'
      path: '/peoplesoft'
      fullPath: '/dashboard/peoplesoft'
      preLoaderRoute: typeof DashboardPeoplesoftRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/approvals': {
      id: '/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preorders/$id': {
      id: '/dashboard/preorders/$id'
      path: '/$id'
      fullPath: '/dashboard/preorders/$id'
      preLoaderRoute: typeof DashboardPreordersIdRouteImport
      parentRoute: typeof DashboardPreordersRoute
    }
    '/dashboard/peoplesoft/lookups': {
      id: '/dashboard/peoplesoft/lookups'
      path: '/lookups'
      fullPath: '/dashboard/peoplesoft/lookups'
      preLoaderRoute: typeof DashboardPeoplesoftLookupsRouteImport
      parentRoute: typeof DashboardPeoplesoftRoute
    }
  }
}

interface DashboardPeoplesoftRouteChildren {
  DashboardPeoplesoftLookupsRoute: typeof DashboardPeoplesoftLookupsRoute
}

const DashboardPeoplesoftRouteChildren: DashboardPeoplesoftRouteChildren = {
  DashboardPeoplesoftLookupsRoute: DashboardPeoplesoftLookupsRoute,
}

const DashboardPeoplesoftRouteWithChildren =
  DashboardPeoplesoftRoute._addFileChildren(DashboardPeoplesoftRouteChildren)

interface DashboardPreordersRouteChildren {
  DashboardPreordersIdRoute: typeof DashboardPreordersIdRoute
}

const DashboardPreordersRouteChildren: DashboardPreordersRouteChildren = {
  DashboardPreordersIdRoute: DashboardPreordersIdRoute,
}

const DashboardPreordersRouteWithChildren =
  DashboardPreordersRoute._addFileChildren(DashboardPreordersRouteChildren)

interface DashboardRouteChildren {
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPeoplesoftRoute: typeof DashboardPeoplesoftRouteWithChildren
  DashboardPreordersRoute: typeof DashboardPreordersRouteWithChildren
  DashboardProvidersRoute: typeof DashboardProvidersRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardResolutionsRoute: typeof DashboardResolutionsRoute
  DashboardSalesRepRoute: typeof DashboardSalesRepRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSupplierPortalRoute: typeof DashboardSupplierPortalRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPeoplesoftRoute: DashboardPeoplesoftRouteWithChildren,
  DashboardPreordersRoute: DashboardPreordersRouteWithChildren,
  DashboardProvidersRoute: DashboardProvidersRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardResolutionsRoute: DashboardResolutionsRoute,
  DashboardSalesRepRoute: DashboardSalesRepRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSupplierPortalRoute: DashboardSupplierPortalRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
